### ISSUE TITLE
Queryparams and headers arguments switched 

### ISSUE THREAD

**Issue by RogerParkinson** [killbill/killbill-plugin-framework-java#30]
Line 167 of org.killbill.billing.plugin.util.http.HttpClient reverses the queryparams and headers arguments. When I pass these two into doCallAndReturn they end up interchanged when they reach the doCall() method on line 170. If I reverse the arguments (ie pass params as headers and vv) then everything works.

**Comment by pierre** [comment]
Thank you for the report - could you send us a pull request?
