### ISSUE TITLE
OSGI Import-Package directives

### ISSUE THREAD

**Issue by beccagaspard** [killbill/killbill-plugin-framework-java#5]
I added the OSGI Import-Package directives as specified in the README.md, but got this error: 

`2016-01-27 12:51:42,041 [bus_ext_events-th] WARN  o.killbill.billing.osgi.FileInstall - Unable to start bundle
org.osgi.framework.BundleException: Unresolved constraint in bundle org.kill-bill.billing.plugin.java.catalog.test [22]: Unable to resolve 22.0: missing requirement [22.0] osgi.wiring.package; (osgi.wiring.package=org.killbill.billing.routing.plugin.api)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        ...`

I removed `org.killbill.billing.routing.plugin.api` from the Import-Package and my plugin started up fine.  Not sure where that package actually comes from (didn't see it in killbill-api) - should it be removed from the README instructions?

**Comment by pierre** [comment]
The `routing` API has been renamed `control`. I've updated the README.

Thanks!
