### ISSUE TITLE
add follow redirect feature to HttpClient

### ISSUE THREAD

**Issue by xsalefter** [killbill/killbill-plugin-framework-java#83]
Currently, base plugin [HttpClient](https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/util/http/HttpClient.java) not get redirected if HTTP response code is 30x. Instead, it's just return something like:
```html
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
</body>
</html>
```

We need to add [`.followRedirects(HttpClient.Redirect.NORMAL)`](https://stackoverflow.com/a/66325588) when [building](https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/util/http/HttpClient.java#L133) an `org.killbill.billing.plugin.util.http.HttpClient`.

**Comment by pierre** [comment]
Can we make the client more flexible?

`buildHttpClient` could return the `HttpClient.Builder` and be `protected`. That way, it's easy to extend?

**Comment by xsalefter** [comment]
Completed by this PR: https://github.com/killbill/killbill-plugin-framework-java/pull/85
