### ISSUE TITLE
Type Implementations

### ISSUE THREAD

**Issue by MaxGfeller** [killbill/killbill-plugin-framework-java#9]
The `createAccount` method on the `accountUserApi` needs a parameter of the type `AccountData` for which only the interface is defined. Not sure if i'm missing something here but i can't find a existing implementation for `AccountData` (and also other types) and ended up implementing one myself.

Is there an existing implementation somewhere?

**Comment by sbrossie** [comment]
Max,

This is correct, the api package only defines interfaces (actually there
are exceptions), and so you would need to implement that interface.

There are obviously implementations on the KB side, but they would force
you to pull jars which we don't suggest you do.

I think you have a point that this is such a common object, everybody (that
writes plugins) will have to end up defining that simple POJO and probably
we should consider adding it in the api package. But also not te common use
case it to create account using JARXS (REST) api for which clients
libraries exist.

Stéphane

**Comment by MaxGfeller** [comment]
Stéphane, thanks for your answer! Instead of having everyone to implement those interfaces i would vote to have those POJOs provided in the framework. Would love to hear what others think of that.

**Comment by pierre** [comment]
We've started implementing POJOs under [org.killbill.billing.plugin.api.core](https://github.com/killbill/killbill-plugin-framework-java/tree/master/src/main/java/org/killbill/billing/plugin/api/core). We'll add more as needed (PR welcome too!).
